### ISSUE TITLE
Input students separated by spaces AND commas

### ISSUE THREAD

**Issue by swaroopjcse** [consider-app/consider#10]
Currently it only takes comma separated; also adding space and newline separated entries shouldn't be a problem.

**Comment by CailinPitt** [comment]
Implemented. Works when emails are separated by commas, spaces, and newlines. I'll submit a pull request.

<img width="281" alt="screen shot 2016-11-01 at 10 58 26 am" src="https://cloud.githubusercontent.com/assets/11185489/19894140/4b683abc-a022-11e6-91fe-cf6a68aa534f.png">

<img width="625" alt="screen shot 2016-11-01 at 10 58 43 am" src="https://cloud.githubusercontent.com/assets/11185489/19894143/50b36410-a022-11e6-8553-526a6ebda983.png">
