### ISSUE TITLE
Prevent application crash when student is not part of a group

### ISSUE THREAD

**Issue by CailinPitt** [consider-app/consider#11]
Not sure if this is much of an issue but during my testing I saw that once the initial round ends, if a Student tries to access the next round before the Instructor has assigned them to a group, the application crashes. This threw me off for a bit while testing my code changes because I thought I had broke something, only to remember I hadn't assigned students to groups. It would be nice to have a splash screen informing the Student to wait for the Instructor to assign them to a group. Once again, not sure if this is much of an issue (since I believe we usually use a buffer/extra round to keep this from happening), but I figured it wouldn't hurt to bring it up.

**Comment by swaroopjcse** [comment]
Yes, that crash should be prevented by redirecting to an error page.

**Comment by CailinPitt** [comment]
![screen shot 2016-11-12 at 5 43 18 pm](https://cloud.githubusercontent.com/assets/11185489/20242552/8e4a1626-a8ff-11e6-878b-0989106de48f.png)

Students are now redirected to error page with error code 106 when they try to access a round when they are not part of a group. Will submit pull request.
